<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Today's Cryptocurrency Prices by Market Cap Generated by CoinMarketCap.">
        <meta name="keywords" content="cryptocurrency">
        
        <link rel="stylesheet" href="css/styles.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="javascript/script.js"></script>

        <title>Top Cryptocurrencies</title>
    </head>
    <body>
        <?php include "includes/header.php"?>

        <main class="container">
            <table id="cryptoTable" class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Symbol</th>
                        <th class="text-end">Price</th>
                        <th class="text-end">Market Cap</th>
                        <th class="text-end">Volume</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- dynamic population of content here -->
                </tbody>
            </table>
        </main>

        <?php include "includes/footer.php"?>
    </body>
</html>