<footer class="container">
    <p>Data Generated by the CoinMarketCap API</p>
    <p>Do not click <a target="_blank" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ&pp=ygUXbmV2ZXIgZ29ubmEgZ2l2ZSB5b3UgdXA%3D">here!</a></p>
</footer>